import { randomUUID } from 'node:crypto';
import type { AccountRepository } from '@main/db/repositories/AccountRepository';
import type { AuditLogRepository } from '@main/db/repositories/AuditLogRepository';
import type { GroupRepository } from '@main/db/repositories/GroupRepository';
import type { PublishRepository } from '@main/db/repositories/PublishRepository';
import type { QueueRepository, QueueRecord } from '@main/db/repositories/QueueRepository';
import { AppError } from '@main/errors';
import { queueIdSchema } from '@shared/schemas';
import type { HealthCheckResult, LiveReadiness, PreflightResult, PublishAttempt, PublishingEngineStatus, PublishingReadiness, PublishingRunResult, ReconciliationRecord, RequeueInput, QueueItem, SelectorProbeResult } from '@shared/types';
import type { MediaStorageService } from '@main/services/MediaStorageService';
import type { PublishCoordinator } from './PublishCoordinator';
import type { PublishDiagnostics } from './PublishDiagnostics';
import type { PublishExecutor } from './PublishExecutor';
import type { PublishScheduler } from './PublishScheduler';
import type { PublishingSettingsService } from './PublishingSettingsService';
import type { LiveReadinessService } from './LiveReadinessService';
import type { OperationsReportService } from './OperationsReportService';

export class PublishingService {
  constructor(private readonly queue: QueueRepository, private readonly attemptsRepository: PublishRepository, private readonly accounts: AccountRepository, private readonly groups: GroupRepository, private readonly media: MediaStorageService, private readonly executor: PublishExecutor, private readonly coordinator: PublishCoordinator, private readonly scheduler: PublishScheduler, private readonly settings: PublishingSettingsService, private readonly diagnostics: PublishDiagnostics, private readonly audit: AuditLogRepository, private readonly notify: () => void, private readonly readiness?: LiveReadinessService, private readonly report?: OperationsReportService) {}

  recover(): number { const count = this.attemptsRepository.recoverRunning('Application stopped during previous publish attempt. Confirm Facebook state before retrying.'); if (count) this.notifySafe(); return count; }
  status(): PublishingEngineStatus {
    const running = this.coordinator.running().map((id) => this.queue.get(id)).filter((item): item is NonNullable<typeof item> => Boolean(item)).map((item) => this.publicItem(item)); const settings = this.settings.get(); const probes = this.attemptsRepository.recentProbes(20); const readiness: PublishingReadiness = this.attemptsRepository.blocks().length ? 'DEGRADED' : settings.executionMode === 'LIVE' && settings.enabled ? 'LIVE_ENABLED' : probes.some((probe) => probe.status === 'FOUND') ? 'PREFLIGHT_READY' : 'NOT_READY';
    const dueCount = typeof this.queue.dueCount === 'function' ? this.queue.dueCount(new Date().toISOString()) : this.queue.due(new Date().toISOString()).length;
    const schedulerArmed = typeof this.scheduler.isArmed === 'function' ? this.scheduler.isArmed() : false;
    return { settings, schedulerRunning: this.scheduler.isRunning(), schedulerArmed, tickRunning: this.scheduler.isTicking(), running, blockedAccounts: this.attemptsRepository.blocks(), recentAttempts: this.attemptsRepository.recent(30), dueCount, overdueCount: dueCount, selectorVersion: this.executor.selectorVersion, readiness, recentProbes: probes };
  }
  run(queueId: string): Promise<PublishingRunResult> { return this.runMany([this.validId(queueId)]); }
  runSelected(queueIds: string[]): Promise<PublishingRunResult> { const ids = queueIds.map((id) => this.validId(id)); const settings = this.settings.get(); if (settings.executionMode === 'LIVE' && settings.canaryMode === true && ids.length > 1) throw new AppError('CANARY_LIMIT', 'Canary mode allows one queue item per explicit run.'); return this.runMany(ids); }
  runDue(): Promise<PublishingRunResult> { const settings = this.settings.get(); if (settings.executionMode === 'LIVE' && settings.canaryMode === true) throw new AppError('CANARY_LIMIT', 'Canary mode disables Run Due. Run one item explicitly.'); return this.scheduler.runDue(); }
  async preflight(queueId: string): Promise<PreflightResult> { const item = this.rawQueue(queueId); if (!['PENDING', 'PAUSED'].includes(item.status)) throw new AppError('INVALID_STATE', 'Only pending or paused queue items can be preflighted.'); const result = await this.executor.preflight(item, this.settings.get(), true); this.notifySafe(); return result; }
  async probe(accountId: string, groupId: string): Promise<SelectorProbeResult> { const account = this.accounts.get(accountId); const group = this.groups.get(groupId); if (!account || !group || !group.active) throw new AppError('GROUP_UNAVAILABLE', 'Account or active group not found.'); if (!this.groups.assignments(groupId).some((assignment) => assignment.id === accountId)) throw new AppError('INVALID_ASSIGNMENT', 'Account is not assigned to this group.'); const item = { id: randomUUID(), accountId, groupId, draftTitle: 'Selector probe', body: '', accountName: account.name, groupName: group.name, groupUrl: group.normalizedUrl, status: 'PENDING' as const, media: [], snapshotHash: 'probe', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; return this.executor.probe(item); }
  attempts(queueId: string): PublishAttempt[] { const id = this.validId(queueId); if (!this.queue.get(id)) throw new AppError('QUEUE_ITEM_NOT_FOUND', 'Queue item not found.'); return this.attemptsRepository.attempts(id); }
  retry(queueId: string, acknowledgeDuplicateRisk: boolean): QueueItem { const id = this.validId(queueId); const item = this.requireQueue(id); const latest = this.attemptsRepository.attempts(id)[0]; if (latest?.irreversibleReached && !acknowledgeDuplicateRisk) throw new AppError('INVALID_REQUEST', 'Retry may create a duplicate Facebook post. Explicit acknowledgement is required.'); try { const updated = this.queue.retry(id); this.auditSafe(item.accountId, 'PUBLISH_RETRY_REQUESTED', 'Queue item prepared for an explicit retry.', id); this.notifySafe(); return this.publicItem(updated); } catch { throw new AppError('INVALID_STATE', 'Queue item cannot be retried from its current state.'); } }
  requeue(input: RequeueInput): QueueItem { const source = this.requireQueue(input.queueId); const account = source.accountId ? this.accounts.get(source.accountId) : undefined; const group = source.groupId ? this.groups.get(source.groupId) : undefined; if (!account || !group || !group.active || !this.groups.assignments(group.id).some((value) => value.id === account.id)) throw new AppError('INVALID_ASSIGNMENT', 'The original account/group target is no longer eligible.'); const timestamp = new Date().toISOString(); try { const item = this.queue.requeue(source.id, randomUUID(), input.scheduledAt, timestamp); this.auditSafe(account.id, 'QUEUE_REQUEUED', 'Queue snapshot requeued as a new item.', item.id); this.notifySafe(); return this.publicItem(item); } catch (error) { if (String(error).toLowerCase().includes('unique')) throw new AppError('DUPLICATE_QUEUE_ITEM', 'An equivalent active queue item already exists.'); throw new AppError('INVALID_STATE', 'Queue item cannot be requeued.'); } }
  resolve(queueId: string): QueueItem { return this.markSubmitted(queueId); }
  markSubmitted(queueId: string): QueueItem { const item = this.requireQueue(queueId); try { this.attemptsRepository.markSubmitted(item.id, 'MANUAL_CONFIRMATION'); this.auditSafe(item.accountId, 'PUBLISH_MANUALLY_MARKED_SUBMITTED', 'Operator reconciled the submission as submitted; public publication remains unverified.', item.id); this.notifySafe(); return this.publicItem(this.queue.get(item.id)!); } catch { throw new AppError('INVALID_STATE', 'Only attention items can be marked submitted.'); } }
  markVerified(queueId: string, evidence?: string): QueueItem { const detail = evidence?.trim(); if (!detail || detail.length > 500) throw new AppError('INVALID_REQUEST', 'Operator evidence is required and must be 500 characters or fewer.'); const item = this.requireQueue(queueId); try { this.attemptsRepository.markVerified(item.id, detail); this.auditSafe(item.accountId, 'PUBLISH_MANUALLY_VERIFIED', 'Operator manually verified publication.', item.id); this.notifySafe(); return this.publicItem(this.queue.get(item.id)!); } catch { throw new AppError('INVALID_STATE', 'Only submitted or attention items with an attempt can be manually verified.'); } }
  reconciliations(queueId: string): ReconciliationRecord[] { const id = this.validId(queueId); return this.attemptsRepository.reconciliations(id); }
  async openDiagnostic(attemptId: string): Promise<void> { const id = this.validId(attemptId); const path = this.attemptsRepository.diagnosticPath(id); if (!path) throw new AppError('INVALID_REQUEST', 'No diagnostic is available for this attempt.'); await this.diagnostics.open(path); }
  async deleteDiagnostic(attemptId: string): Promise<void> { const id = this.validId(attemptId); const path = this.attemptsRepository.diagnosticPath(id); if (!path) throw new AppError('INVALID_REQUEST', 'No diagnostic is available for this attempt.'); await this.diagnostics.delete(path); this.attemptsRepository.clearDiagnostic(id); this.notifySafe(); }
  handleHealthResult(result: HealthCheckResult): void { if (result.status === 'READY' && this.attemptsRepository.clearBlock(result.accountId)) { this.auditSafe(result.accountId, 'ACCOUNT_PUBLISHING_RESUMED', 'Publishing resumed after a successful health check.', result.accountId); this.notifySafe(); } }
  async evaluateLiveReadiness(queueId: string): Promise<LiveReadiness> { const item = this.rawQueue(queueId); if (!this.readiness) return { ready: false, reasons: ['PREFLIGHT_MISSING'] }; this.readiness.setSelectorVersion(this.executor.selectorVersion); return this.readiness.evaluate(item, this.settings.get()); }
  armScheduler(acknowledgeOverdue = false): PublishingEngineStatus { try { this.scheduler.arm(acknowledgeOverdue); } catch (error) { const message = error instanceof Error ? error.message : 'Scheduler could not be armed.'; throw new AppError(message.toLowerCase().includes('canary') ? 'CANARY_LIMIT' : 'OVERDUE_BACKLOG_ACK_REQUIRED', message); } this.coordinator.resumeAccepting(); this.auditSafe(undefined, 'PUBLISH_SCHEDULER_ARMED', 'Scheduler armed for this application session.'); this.notifySafe(); return this.status(); }
  disarmScheduler(): PublishingEngineStatus { this.scheduler.disarm(); this.auditSafe(undefined, 'PUBLISH_SCHEDULER_DISARMED', 'Scheduler disarmed.'); this.notifySafe(); return this.status(); }
  async stopPublishing(): Promise<PublishingEngineStatus> { this.scheduler.disarm(); await this.coordinator.stopAndDrain(20000); this.auditSafe(undefined, 'PUBLISHING_STOPPED', 'Publishing stopped and scheduler disarmed.'); this.notifySafe(); return this.status(); }
  async exportReport(): Promise<string | undefined> { if (!this.report) throw new AppError('INVALID_STATE', 'Operations report is unavailable.'); return this.report.chooseAndExport(); }

  private async runMany(ids: string[]): Promise<PublishingRunResult> { const unique = [...new Set(ids)]; if (this.settings.get().executionMode === 'DRY_RUN') { for (const id of unique) await this.preflight(id); return { requested: unique.length, claimed: 0, completed: 0, skipped: unique.length }; } return this.coordinator.run(unique, this.settings.get()); }
  private requireQueue(value: string): QueueItem { const item = this.queue.get(this.validId(value)); if (!item) throw new AppError('QUEUE_ITEM_NOT_FOUND', 'Queue item not found.'); return this.publicItem(item); }
  private validId(value: string): string { const parsed = queueIdSchema.safeParse(value); if (!parsed.success) throw new AppError('INVALID_REQUEST', 'Invalid identifier.'); return parsed.data; }
  private rawQueue(value: string): QueueRecord { const item = this.queue.get(this.validId(value)); if (!item) throw new AppError('QUEUE_ITEM_NOT_FOUND', 'Queue item not found.'); return item; }
  private publicItem(item: ReturnType<QueueRepository['get']> extends infer T ? NonNullable<T> : never): QueueItem { return { ...item, media: item.media.map((asset) => ({ id: asset.id, type: asset.type, originalName: asset.originalName, mimeType: asset.mimeType, fileSize: asset.fileSize, sortOrder: asset.sortOrder, previewUrl: this.media.previewUrl(asset.id) })) }; }
  private auditSafe(accountId: string | undefined, eventType: string, message: string, queueId?: string): void { try { this.audit.add({ accountId, eventType, message, metadata: JSON.stringify(queueId ? { queueId } : {}) }); } catch { /* best effort */ } }
  private notifySafe(): void { try { this.notify(); } catch { /* renderer may be closing */ } }
}
