import type { ApiErrorCode } from '@shared/types';

export class PublishingError extends Error {
  constructor(public readonly code: Extract<ApiErrorCode, 'ACCOUNT_LOGIN_REQUIRED' | 'ACCOUNT_CHECKPOINT' | 'GROUP_UNAVAILABLE' | 'GROUP_PERMISSION_DENIED' | 'COMPOSER_NOT_FOUND' | 'COMPOSER_TRIGGER_NOT_FOUND' | 'COMPOSER_TRIGGER_AMBIGUOUS' | 'COMPOSER_TRIGGER_CLICK_FAILED' | 'COMPOSER_TRIGGER_CLICK_NO_COMPOSER' | 'COMPOSER_CONTAINER_NOT_FOUND' | 'COMPOSER_TEXTBOX_NOT_FOUND' | 'COMPOSER_TEXTBOX_AMBIGUOUS' | 'CONTENT_FILL_FAILED' | 'MEDIA_FILE_MISSING' | 'MEDIA_UPLOAD_FAILED' | 'MEDIA_UPLOAD_TIMEOUT' | 'SUBMIT_FAILED' | 'SUBMISSION_UNKNOWN' | 'NETWORK_ERROR' | 'BROWSER_CLOSED' | 'EXECUTION_CANCELLED' | 'LIVE_READINESS_FAILED'>, message: string, public readonly afterSubmit = false) { super(message); this.name = 'PublishingError'; }
}
