import { afterEach, describe, expect, it, vi } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createAppPaths, openDatabase } from '@main/db/database';
import { AccountRepository } from '@main/db/repositories/AccountRepository';
import { AccountSessionRepository } from '@main/db/repositories/AccountSessionRepository';
import { OnboardingRepository } from '@main/db/repositories/OnboardingRepository';
import { GroupRepository } from '@main/db/repositories/GroupRepository';
import { AuditLogRepository } from '@main/db/repositories/AuditLogRepository';
import { SettingsRepository } from '@main/db/repositories/SettingsRepository';
import { OnboardingService } from './OnboardingService';
import { AccountSessionService, type AccountSessionScheduler } from './AccountSessionService';
import type { AccountService } from './AccountService';

const roots: string[] = [];
afterEach(() => { for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }); });

class FakeScheduler implements AccountSessionScheduler {
  private sequence = 0; private readonly pending = new Map<number, { due: number; callback: () => void }>(); readonly callbacks: Array<() => void> = [];
  constructor(private readonly currentTime: () => number) {}
  schedule(callback: () => void, delayMs: number): unknown { const id = ++this.sequence; this.pending.set(id, { due: this.currentTime() + delayMs, callback }); this.callbacks.push(callback); return id; }
  cancel(handle: unknown): void { this.pending.delete(handle as number); }
  runDue(): void { while (true) { const next = [...this.pending].filter(([, task]) => task.due <= this.currentTime()).sort((left, right) => left[1].due - right[1].due)[0]; if (!next) return; this.pending.delete(next[0]); next[1].callback(); } }
  get size(): number { return this.pending.size; }
}

function fixture(proxyEnabled = false, initialClock = new Date('2026-01-01T00:00:00.000Z')) {
  const root = mkdtempSync(join(tmpdir(), 'account-session-')); roots.push(root); const db = openDatabase(createAppPaths(root)); const accounts = new AccountRepository(db); const sessions = new AccountSessionRepository(db); const onboardingRepository = new OnboardingRepository(db); const groups = new GroupRepository(db); const audit = new AuditLogRepository(db); const settings = new SettingsRepository(db); let clock = new Date(initialClock); const scheduler = new FakeScheduler(() => clock.getTime()); const id = randomUUID();
  accounts.insert({ id, name: 'Session account', profileName: `session-${id}`, profileDirectory: join(root, 'profile'), proxyEnabled, proxyProtocol: 'HTTP', proxyHost: proxyEnabled ? 'proxy.example.com' : undefined, proxyPort: proxyEnabled ? 8080 : undefined, createdAt: clock.toISOString(), updatedAt: clock.toISOString() });
  const onboarding = new OnboardingService(onboardingRepository, accounts, groups, audit, vi.fn(), () => clock); onboarding.start({ accountId: id, templateId: 'BASIC_3_DAY' });
  const browser = { isRunning: vi.fn(() => false), navigateSessionPage: vi.fn(async () => ({ accountId: id, status: 'OPENED' as const })), navigateAccountPage: vi.fn(async () => ({ accountId: id, status: 'OPENED' as const })) };
  const accountService = { browser, reportHealthResult: vi.fn(), testProxy: vi.fn(async () => ({ success: true, testedAt: clock.toISOString(), ip: '203.0.113.8' })), healthCheck: vi.fn(async () => { accounts.setHealth(id, 'READY', clock.toISOString()); return { accountId: id, status: 'READY' as const, checkedAt: clock.toISOString() }; }), open: vi.fn(async () => { accounts.setStatus(id, 'RUNNING'); return accounts.get(id)!; }), close: vi.fn(async () => { accounts.setStatus(id, 'STOPPED'); return accounts.get(id)!; }) } as unknown as AccountService;
  const notify = vi.fn(); const service = new AccountSessionService(sessions, onboardingRepository, accounts, groups, settings, accountService, onboarding, audit, notify, () => clock, scheduler);
  const elapse = (milliseconds: number, runTimers = true) => { clock = new Date(clock.getTime() + milliseconds); if (runTimers) scheduler.runDue(); };
  const closeBrowser = async () => { await accountService.close(id); service.handleBrowserClosed(id); };
  return { root, db, accounts, sessions, onboardingRepository, groups, audit, settings, onboarding, browser, accountService, service, scheduler, notify, id, elapse, closeBrowser, now: () => clock };
}

function setTarget(value: ReturnType<typeof fixture>, minutes: number, autoCloseBrowserAfterTarget = false) { value.service.updateSettings({ targetDurationMinutes: minutes, autoCloseBrowserAfterTarget }); }
function eventCount(value: ReturnType<typeof fixture>, type: string): number { return value.audit.list({ eventType: type }).length; }

describe('deterministic account-session target completion', () => {
  it('defaults to 30 minutes and reads legacy JSON with auto-close disabled', () => { const value = fixture(); expect(value.service.settings()).toEqual({ targetDurationMinutes: 30, autoCloseBrowserAfterTarget: false }); value.settings.set('account-session:settings', JSON.stringify({ targetDurationMinutes: 15 })); expect(value.service.settings()).toEqual({ targetDurationMinutes: 15, autoCloseBrowserAfterTarget: false }); expect(() => value.service.updateSettings({ targetDurationMinutes: 9, autoCloseBrowserAfterTarget: false })).toThrowError(expect.objectContaining({ code: 'INVALID_REQUEST' })); value.db.close(); });

  it('stays ACTIVE at 29:59 and completes in main at 30:00 without renderer involvement', async () => { const value = fixture(); await value.service.start({ accountId: value.id }); value.elapse(1_799_000); expect(value.service.detail(value.id).activeSession?.status).toBe('ACTIVE'); value.elapse(1_000); expect(value.service.detail(value.id)).toMatchObject({ activeSession: undefined, sessions: [expect.objectContaining({ status: 'COMPLETED', completionReason: 'TARGET_REACHED', durationSeconds: 1800 })] }); expect(value.scheduler.size).toBe(0); expect(value.notify).toHaveBeenCalled(); value.db.close(); });

  it('suspends remaining time while paused and reschedules only active duration', async () => { const value = fixture(); await value.service.start({ accountId: value.id }); value.elapse(600_000); expect(value.service.pause(value.id).activeSession).toMatchObject({ status: 'PAUSED', durationSeconds: 600 }); expect(value.scheduler.size).toBe(0); value.elapse(1_800_000); expect(value.service.detail(value.id).activeSession).toMatchObject({ status: 'PAUSED', durationSeconds: 600 }); value.service.resume(value.id); value.elapse(1_199_000); expect(value.service.detail(value.id).activeSession?.status).toBe('ACTIVE'); value.elapse(1_000); expect(value.service.detail(value.id).sessions[0]).toMatchObject({ completionReason: 'TARGET_REACHED', durationSeconds: 1800 }); value.db.close(); });

  it('normalizes browser close before versus at the target boundary', async () => { const early = fixture(); await early.service.start({ accountId: early.id }); early.elapse(1_799_000, false); early.service.handleBrowserClosed(early.id); expect(early.service.detail(early.id).sessions[0]).toMatchObject({ status: 'INTERRUPTED', completionReason: 'BROWSER_CLOSED', durationSeconds: 1799 }); early.db.close(); const reached = fixture(); await reached.service.start({ accountId: reached.id }); reached.elapse(1_800_000, false); reached.service.handleBrowserClosed(reached.id); expect(reached.service.detail(reached.id).sessions[0]).toMatchObject({ status: 'COMPLETED', completionReason: 'TARGET_REACHED', durationSeconds: 1800 }); reached.db.close(); });

  it('normalizes operator End before versus at target', async () => { const early = fixture(); await early.service.start({ accountId: early.id }); early.elapse(1_200_000, false); const ended = early.service.end({ accountId: early.id }); expect(ended.sessions[0]).toMatchObject({ status: 'COMPLETED', completionReason: 'OPERATOR_ENDED', durationSeconds: 1200 }); expect(ended.dailyProgress[0].completed).toBe(false); early.db.close(); const reached = fixture(); await reached.service.start({ accountId: reached.id }); reached.elapse(1_800_000, false); expect(reached.service.end({ accountId: reached.id }).sessions[0]).toMatchObject({ status: 'COMPLETED', completionReason: 'TARGET_REACHED' }); reached.db.close(); });

  it('keeps checkpoint priority below target and pauses onboarding', async () => { const value = fixture(); await value.service.start({ accountId: value.id }); value.elapse(1_740_000, false); value.accounts.setHealth(value.id, 'CHECKPOINT', value.now().toISOString(), 'Manual action required.'); value.service.handleHealthResult({ accountId: value.id, status: 'CHECKPOINT', checkedAt: value.now().toISOString() }); expect(value.service.detail(value.id).sessions[0]).toMatchObject({ status: 'INTERRUPTED', completionReason: 'HEALTH_INTERRUPTED', durationSeconds: 1740 }); expect(value.accounts.get(value.id)?.onboardingStatus).toBe('PAUSED'); value.db.close(); });

  it('makes target/browser and target/health races idempotent', async () => { const browserRace = fixture(); await browserRace.service.start({ accountId: browserRace.id }); browserRace.elapse(1_800_000); browserRace.service.handleBrowserClosed(browserRace.id); expect(browserRace.service.detail(browserRace.id).sessions).toHaveLength(1); expect(eventCount(browserRace, 'ACCOUNT_SESSION_TARGET_REACHED')).toBe(1); browserRace.db.close(); const healthRace = fixture(); await healthRace.service.start({ accountId: healthRace.id }); healthRace.elapse(1_800_000); healthRace.accounts.setHealth(healthRace.id, 'CHECKPOINT', healthRace.now().toISOString()); healthRace.service.handleHealthResult({ accountId: healthRace.id, status: 'CHECKPOINT', checkedAt: healthRace.now().toISOString() }); expect(eventCount(healthRace, 'ACCOUNT_SESSION_TARGET_REACHED')).toBe(1); expect(healthRace.accounts.get(healthRace.id)?.onboardingStatus).toBe('PAUSED'); healthRace.db.close(); });

  it('prevents a cancelled old timeout from completing a newer session', async () => { const value = fixture(); await value.service.start({ accountId: value.id }); const stale = value.scheduler.callbacks[0]; value.elapse(300_000, false); value.service.end({ accountId: value.id }); await value.accountService.close(value.id); await value.service.start({ accountId: value.id }); stale(); expect(value.service.detail(value.id).activeSession?.status).toBe('ACTIVE'); expect(value.service.detail(value.id).sessions[0].status).toBe('ACTIVE'); value.db.close(); });

  it('cancels watchdogs on emergency stop and application shutdown', async () => { const emergency = fixture(); await emergency.service.start({ accountId: emergency.id }); expect(await emergency.service.stopAll()).toBe(1); expect(emergency.scheduler.size).toBe(0); emergency.elapse(1_800_000); expect(emergency.service.detail(emergency.id).sessions[0].completionReason).toBe('EMERGENCY_STOP'); emergency.db.close(); const shutdown = fixture(); await shutdown.service.start({ accountId: shutdown.id }); expect(await shutdown.service.stopAll('APPLICATION_SHUTDOWN')).toBe(1); expect(shutdown.scheduler.size).toBe(0); expect(shutdown.service.detail(shutdown.id).sessions[0].completionReason).toBe('APPLICATION_SHUTDOWN'); shutdown.db.close(); });

  it('recovers below target as interrupted and reached target as complete', () => { const below = fixture(); below.sessions.start({ id: randomUUID(), accountId: below.id, onboardingDay: 1, targetDurationSeconds: 1800, timestamp: below.now().toISOString() }); below.elapse(1_799_000, false); expect(below.service.recoverAbandoned()).toBe(1); expect(below.service.detail(below.id).sessions[0]).toMatchObject({ status: 'INTERRUPTED', completionReason: 'APPLICATION_RESTART', durationSeconds: 1799 }); below.db.close(); const reached = fixture(); reached.sessions.start({ id: randomUUID(), accountId: reached.id, onboardingDay: 1, targetDurationSeconds: 1800, timestamp: reached.now().toISOString() }); reached.elapse(1_800_000, false); expect(reached.service.recoverAbandoned()).toBe(1); expect(reached.service.detail(reached.id).sessions[0]).toMatchObject({ status: 'COMPLETED', completionReason: 'TARGET_REACHED', durationSeconds: 1800 }); reached.db.close(); });

  it('reconciles PAUSED recovery from persisted active duration without counting pause time', () => { const below = fixture(); below.sessions.start({ id: randomUUID(), accountId: below.id, onboardingDay: 1, targetDurationSeconds: 600, timestamp: below.now().toISOString() }); below.elapse(599_000, false); below.sessions.pause(below.id, below.now().toISOString()); below.elapse(3_600_000, false); below.service.recoverAbandoned(); expect(below.service.detail(below.id).sessions[0]).toMatchObject({ status: 'INTERRUPTED', completionReason: 'APPLICATION_RESTART', durationSeconds: 599 }); below.db.close(); const reached = fixture(); reached.sessions.start({ id: randomUUID(), accountId: reached.id, onboardingDay: 1, targetDurationSeconds: 600, timestamp: reached.now().toISOString() }); reached.elapse(600_000, false); reached.sessions.pause(reached.id, reached.now().toISOString()); reached.elapse(3_600_000, false); reached.service.recoverAbandoned(); expect(reached.service.detail(reached.id).sessions[0]).toMatchObject({ status: 'COMPLETED', completionReason: 'TARGET_REACHED', durationSeconds: 600 }); reached.db.close(); });

  it('preserves historical target integrity when current settings change', () => { const long = fixture(); const id = randomUUID(); long.sessions.start({ id, accountId: long.id, onboardingDay: 1, targetDurationSeconds: 1800, timestamp: long.now().toISOString() }); long.elapse(1_200_000, false); long.sessions.finishById(id, 'COMPLETED', 'OPERATOR_ENDED', 'READY', undefined, long.now().toISOString()); setTarget(long, 10); expect(long.service.detail(long.id).dailyProgress[0]).toMatchObject({ durationSeconds: 1200, targetDurationSeconds: 1800, completed: false }); long.db.close(); const short = fixture(); const shortId = randomUUID(); short.sessions.start({ id: shortId, accountId: short.id, onboardingDay: 1, targetDurationSeconds: 600, timestamp: short.now().toISOString() }); short.elapse(600_000, false); short.sessions.finishById(shortId, 'COMPLETED', 'TARGET_REACHED', 'READY', undefined, short.now().toISOString()); setTarget(short, 30); expect(short.service.detail(short.id).dailyProgress[0]).toMatchObject({ durationSeconds: 600, targetDurationSeconds: 600, completed: true }); short.db.close(); });

  it('accumulates multiple same-day sessions and schedules only remaining daily time', async () => { const value = fixture(); setTarget(value, 30); await value.service.start({ accountId: value.id }); value.elapse(600_000, false); value.service.end({ accountId: value.id }); await value.accountService.close(value.id); await value.service.start({ accountId: value.id }); value.elapse(480_000, false); value.service.end({ accountId: value.id }); await value.accountService.close(value.id); await value.service.start({ accountId: value.id }); value.elapse(719_000); expect(value.service.detail(value.id).activeSession?.status).toBe('ACTIVE'); value.elapse(1_000); const detail = value.service.detail(value.id); expect(detail.sessions[0]).toMatchObject({ status: 'COMPLETED', completionReason: 'TARGET_REACHED', durationSeconds: 720 }); expect(detail.dailyProgress[0]).toMatchObject({ durationSeconds: 1800, targetDurationSeconds: 1800, completed: true }); value.db.close(); });

  it('reports authoritative accumulated progress live across pause, resume, and a lower new-session target', async () => {
    const value = fixture(); setTarget(value, 30); await value.service.start({ accountId: value.id }); value.elapse(1_200_000, false); value.service.end({ accountId: value.id }); await value.accountService.close(value.id);
    setTarget(value, 10); await value.service.start({ accountId: value.id }); expect(value.service.detail(value.id).dailyProgress[0]).toMatchObject({ durationSeconds: 1200, targetDurationSeconds: 1800, completed: false });
    value.elapse(300_000, false); expect(value.service.detail(value.id).dailyProgress[0]).toMatchObject({ durationSeconds: 1500, targetDurationSeconds: 1800, completed: false });
    value.service.pause(value.id); value.elapse(3_600_000, false); expect(value.service.detail(value.id).dailyProgress[0]).toMatchObject({ durationSeconds: 1500, targetDurationSeconds: 1800, completed: false });
    value.service.resume(value.id); value.elapse(300_000); expect(value.service.detail(value.id).dailyProgress[0]).toMatchObject({ durationSeconds: 1800, targetDurationSeconds: 1800, completed: true }); expect(value.service.detail(value.id).sessions[0]).toMatchObject({ completionReason: 'TARGET_REACHED', durationSeconds: 600, targetDurationSeconds: 600 }); value.db.close();
  });

  it('keeps a session on its start day across midnight and assigns the next session to the new day', async () => {
    const start = new Date(2026, 7, 25, 23, 50); const value = fixture(false, start); setTarget(value, 30); await value.service.start({ accountId: value.id }); expect(value.service.detail(value.id).activeSession?.onboardingDay).toBe(1);
    value.elapse(1_800_000); const completed = value.service.detail(value.id); expect(completed.sessions[0]).toMatchObject({ onboardingDay: 1, completionReason: 'TARGET_REACHED', durationSeconds: 1800 }); expect(completed.dailyProgress[0].completed).toBe(true);
    await value.accountService.close(value.id); await value.service.start({ accountId: value.id }); expect(value.service.detail(value.id).activeSession?.onboardingDay).toBe(2); expect(value.service.detail(value.id).dailyProgress[0]).toMatchObject({ durationSeconds: 1800, targetDurationSeconds: 1800, completed: true }); value.db.close();
  });

  it('needs only ten additional active minutes after twenty minutes accumulated', async () => { const value = fixture(); setTarget(value, 30); await value.service.start({ accountId: value.id }); value.elapse(1_200_000, false); value.service.end({ accountId: value.id }); await value.accountService.close(value.id); await value.service.start({ accountId: value.id }); value.elapse(599_000); expect(value.service.detail(value.id).activeSession?.status).toBe('ACTIVE'); value.elapse(1_000); expect(value.service.detail(value.id).sessions[0]).toMatchObject({ completionReason: 'TARGET_REACHED', durationSeconds: 600 }); value.db.close(); });

  it('persists actual active time when a watchdog callback runs late', async () => { const value = fixture(); await value.service.start({ accountId: value.id }); value.elapse(1_801_000); expect(value.service.detail(value.id).sessions[0]).toMatchObject({ completionReason: 'TARGET_REACHED', durationSeconds: 1801 }); value.db.close(); });

  it('rejects a new managed session when today is already complete', async () => { const value = fixture(); const id = randomUUID(); value.sessions.start({ id, accountId: value.id, onboardingDay: 1, targetDurationSeconds: 600, timestamp: value.now().toISOString() }); value.elapse(600_000, false); value.sessions.finishById(id, 'COMPLETED', 'TARGET_REACHED', 'READY', undefined, value.now().toISOString()); setTarget(value, 10); await expect(value.service.start({ accountId: value.id })).rejects.toMatchObject({ code: 'DAILY_SESSION_TARGET_ALREADY_REACHED' }); expect(value.accountService.healthCheck).not.toHaveBeenCalled(); value.db.close(); });

  it('leaves browser open by default and finalizes before optional auto-close', async () => { const open = fixture(); setTarget(open, 10, false); await open.service.start({ accountId: open.id }); open.elapse(600_000); expect(open.accountService.close).not.toHaveBeenCalled(); open.db.close(); const close = fixture(); setTarget(close, 10, true); vi.mocked(close.accountService.close).mockImplementationOnce(async () => { expect(close.sessions.active(close.id)).toBeUndefined(); close.accounts.setStatus(close.id, 'STOPPED'); return close.accounts.get(close.id)!; }); await close.service.start({ accountId: close.id }); close.elapse(600_000); await vi.waitFor(() => expect(close.accountService.close).toHaveBeenCalledTimes(1)); close.service.handleBrowserClosed(close.id); expect(close.service.detail(close.id).sessions[0]).toMatchObject({ status: 'COMPLETED', completionReason: 'TARGET_REACHED' }); close.db.close(); });

  it('updates dashboard counts and daily task exactly once at auto completion', async () => { const value = fixture(); setTarget(value, 10); await value.service.start({ accountId: value.id }); expect(value.sessions.dashboard('2026-01-01T00:00:00.000Z', '2026-01-02T00:00:00.000Z', value.now().toISOString()).activeNow).toBe(1); value.elapse(600_000); expect(value.sessions.dashboard('2026-01-01T00:00:00.000Z', '2026-01-02T00:00:00.000Z', value.now().toISOString())).toMatchObject({ activeNow: 0, dailyTargetsCompleted: 1, minutesToday: 10 }); value.service.handleBrowserClosed(value.id); expect(value.sessions.dashboard('2026-01-01T00:00:00.000Z', '2026-01-02T00:00:00.000Z', value.now().toISOString()).dailyTargetsCompleted).toBe(1); expect(value.onboardingRepository.tasks(value.id).filter((task) => task.dayNumber === 1 && task.type === 'MANUAL_TASK' && task.title.toLowerCase().includes('session') && task.status === 'DONE')).toHaveLength(1); value.db.close(); });

  it('retains proxy preflight, health preflight, and explicit navigation behavior', async () => { const value = fixture(true); await value.service.start({ accountId: value.id }); expect(value.accountService.testProxy).toHaveBeenCalledBefore(value.accountService.healthCheck as never); expect(value.accountService.healthCheck).toHaveBeenCalledBefore(value.accountService.open as never); await value.service.navigate({ accountId: value.id, destination: 'HOME' }); expect(value.browser.navigateSessionPage).toHaveBeenCalledTimes(1); value.db.close(); });
});
