import { useCallback, useEffect, useState } from 'react';
import type { AuditLog, FacebookAccount, LogFilter } from '@shared/types';

export function LogsPage({ accounts }: { accounts: FacebookAccount[] }) {
  const [logs, setLogs] = useState<AuditLog[]>([]); const [accountId, setAccountId] = useState(''); const [eventType, setEventType] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const filter: LogFilter = {}; if (accountId) filter.accountId = accountId; if (eventType) filter.eventType = eventType; if (from) filter.from = new Date(from).toISOString(); if (to) filter.to = new Date(to).toISOString(); setLogs(await window.logApi.list(filter)); } finally { setLoading(false); } }, [accountId, eventType, from, to]);
  useEffect(() => { void load(); }, [load]);
  const eventTypes = [...new Set(logs.map((log) => log.eventType))];
  return <main className="content"><div className="page-heading"><div><h2>Audit logs</h2><p>Lifecycle and health events. Sensitive credentials and session data are never logged.</p></div></div><div className="filters"><label>Account<select value={accountId} onChange={(e) => setAccountId(e.target.value)}><option value="">All accounts</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Event<select value={eventType} onChange={(e) => setEventType(e.target.value)}><option value="">All events</option>{eventTypes.map((event) => <option key={event} value={event}>{event}</option>)}</select></label><label>From<input type="datetime-local" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label>To<input type="datetime-local" value={to} onChange={(e) => setTo(e.target.value)} /></label><button className="secondary filter-refresh" onClick={() => void load()}>Refresh</button></div>{loading ? <div className="empty-state">Loading logs…</div> : <div className="table-card"><div className="table-wrap"><table><thead><tr><th>Time</th><th>Account</th><th>Event</th><th>Message</th></tr></thead><tbody>{logs.length ? logs.map((log) => <tr key={log.id}><td>{new Date(log.createdAt).toLocaleString([], { dateStyle: 'short', timeStyle: 'medium' })}</td><td>{log.accountName ?? log.accountId?.slice(0, 8) ?? 'System'}</td><td><span className="event-pill">{log.eventType}</span></td><td>{log.message}</td></tr>) : <tr><td colSpan={4} className="empty-cell">No matching events.</td></tr>}</tbody></table></div></div>}</main>;
}
