import { useCallback, useEffect, useMemo, useState } from 'react';
import type { AccountOnboarding, FacebookGroup, OnboardingOverview, OnboardingPlanTemplate, WarmUpTask } from '@shared/types';

export function OnboardingPage({ initialAccountId, onError }: { initialAccountId?: string; onError: (error: unknown) => void }) {
  const [overview, setOverview] = useState<OnboardingOverview>(); const [templates, setTemplates] = useState<OnboardingPlanTemplate[]>([]); const [selectedId, setSelectedId] = useState(initialAccountId ?? ''); const [detail, setDetail] = useState<AccountOnboarding>(); const [groups, setGroups] = useState<FacebookGroup[]>([]); const [templateId, setTemplateId] = useState<'BASIC_3_DAY' | 'BASIC_5_DAY'>('BASIC_3_DAY'); const [notes, setNotes] = useState(''); const [editing, setEditing] = useState<WarmUpTask>(); const [busy, setBusy] = useState(''); const [now, setNow] = useState(Date.now()); const [notice, setNotice] = useState('');
  const loadOverview = useCallback(async () => { try { const value = await window.onboardingApi.overview(); setOverview(value); if (!selectedId && value.accounts.length) setSelectedId(value.accounts[0].account.id); } catch (error) { onError(error); } }, [onError, selectedId]);
  const loadDetail = useCallback(async () => { if (!selectedId) { setDetail(undefined); return; } try { const [value, assigned] = await Promise.all([window.onboardingApi.get(selectedId), window.groupApi.accountGroups(selectedId)]); setDetail(value); setNotes(value.account.onboardingNotes ?? ''); setGroups(assigned.filter((group) => group.active)); } catch (error) { onError(error); } }, [onError, selectedId]);
  useEffect(() => { void window.onboardingApi.templates().then(setTemplates).catch(onError); void loadOverview(); const unsubscribe = window.onboardingApi.onChanged(() => { void loadOverview(); void loadDetail(); }); return unsubscribe; }, [loadDetail, loadOverview, onError]);
  useEffect(() => { void loadDetail(); }, [loadDetail]);
  useEffect(() => { if (!detail?.activeSession) return; const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, [detail?.activeSession]);
  async function perform(label: string, operation: () => Promise<unknown>) { setBusy(label); setNotice(''); try { await operation(); await Promise.all([loadOverview(), loadDetail()]); } catch (error) { onError(error); } finally { setBusy(''); } }
  async function taskAction(task: WarmUpTask) {
    if (task.type === 'OPEN_FACEBOOK') await perform(task.id, () => window.accountApi.open(task.accountId));
    else if (task.type === 'OPEN_GROUP') { if (!task.groupId) { setNotice('Choose an assigned group for this task first.'); return; } await perform(task.id, () => window.groupApi.open(task.groupId!, task.accountId)); }
    else if (task.type === 'HEALTH_CHECK') await perform(task.id, async () => { const result = await window.accountApi.healthCheck(task.accountId); setNotice(`Health check: ${result.status}${result.reason ? ` · ${result.reason}` : ''}`); });
  }
  const activeSeconds = useMemo(() => detail?.activeSession ? Math.max(0, Math.floor((now - Date.parse(detail.activeSession.startedAt)) / 1000)) : 0, [detail?.activeSession, now]);
  return <main className="content"><div className="page-heading"><div><h2>Account Onboarding</h2><p>Human-in-the-loop plans, manual checklists, and local session tracking. No Facebook interactions are automated.</p></div><button className="secondary" onClick={() => void Promise.all([loadOverview(), loadDetail()])}>Refresh</button></div>
    {overview && <div className="stat-grid onboarding-stats"><div className="stat-card"><small>New accounts</small><strong>{overview.counts.NEW}</strong><span>not started</span></div><div className="stat-card"><small>Warming accounts</small><strong>{overview.counts.WARMING}</strong><span>operator plans active</span></div><div className="stat-card"><small>Ready accounts</small><strong>{overview.counts.READY}</strong><span>explicitly marked</span></div><div className="stat-card"><small>Paused onboarding</small><strong>{overview.counts.PAUSED}</strong><span>manual action required</span></div><div className="stat-card"><small>Today's tasks</small><strong>{overview.todayTasks.length}</strong><span>{overview.completedToday} completed today</span></div></div>}
    {overview && <div className="dashboard-grid onboarding-overview"><section className="panel"><div className="panel-heading"><h3>Today's onboarding tasks</h3><span>{overview.todayTasks.length}</span></div>{overview.todayTasks.length ? <div className="stack-list">{overview.todayTasks.slice(0, 12).map((task) => <button className="stack-row onboarding-summary-row" key={task.id} onClick={() => setSelectedId(task.accountId)}><div><strong>{overview.accounts.find((item) => item.account.id === task.accountId)?.account.name} · {task.title}</strong><small>Day {task.dayNumber} · {task.status}</small></div></button>)}</div> : <div className="muted-block">No onboarding tasks for the current plan day.</div>}</section><section className="panel"><div className="panel-heading"><h3>Paused accounts</h3><span>{overview.pausedAccounts.length}</span></div>{overview.pausedAccounts.length ? <div className="stack-list">{overview.pausedAccounts.map((account) => <button className="stack-row onboarding-summary-row" key={account.id} onClick={() => setSelectedId(account.id)}><div><strong>{account.name}</strong><small>{account.onboardingPausedReason ?? 'Manual action required.'}</small></div></button>)}</div> : <div className="muted-block">No onboarding accounts are paused.</div>}</section></div>}
    {notice && <div className="notice success"><span>{notice}</span><button onClick={() => setNotice('')}>×</button></div>}
    <div className="onboarding-layout"><section className="panel onboarding-account-list"><div className="panel-heading"><h3>Accounts requiring onboarding</h3><span>{overview?.accounts.length ?? 0}</span></div>{overview?.accounts.map((item) => <button key={item.account.id} className={selectedId === item.account.id ? 'onboarding-account active' : 'onboarding-account'} onClick={() => setSelectedId(item.account.id)}><strong>{item.account.name}</strong><span className={`status-badge status-${item.account.onboardingStatus.toLowerCase()}`}>{item.account.onboardingStatus}</span><small>{item.currentDay ? `Day ${item.currentDay} of ${item.account.onboardingPlanDays}` : 'Plan not started'} · {item.completedTasks}/{item.totalTasks} done</small></button>)}</section>
      <section className="panel onboarding-detail">{!detail ? <div className="muted-block">Select an account.</div> : <><div className="panel-heading"><div><h3>{detail.account.name}</h3><small>Session {detail.account.lastHealthStatus ?? 'UNKNOWN'} · Proxy {detail.account.proxyEnabled ? detail.account.proxyStatus : 'DIRECT'}</small></div><span className={`status-badge status-${detail.account.onboardingStatus.toLowerCase()}`}>{detail.account.onboardingStatus}</span></div>
        {detail.account.onboardingPausedReason && <div className="inline-warning">Paused: {detail.account.onboardingPausedReason}</div>}
        {detail.account.onboardingStatus === 'NEW' && <div className="onboarding-start"><label>Operator onboarding plan<select value={templateId} onChange={(event) => setTemplateId(event.target.value as typeof templateId)}>{templates.map((template) => <option key={template.id} value={template.id}>{template.name} · {template.days} days</option>)}</select></label><p>{templates.find((template) => template.id === templateId)?.description}</p><button className="primary" disabled={Boolean(busy)} onClick={() => void perform('start', () => window.onboardingApi.start({ accountId: detail.account.id, templateId }))}>Start onboarding</button></div>}
        {detail.account.onboardingStatus !== 'NEW' && <><div className="onboarding-toolbar"><div><strong>{detail.currentDay ? `Day ${detail.currentDay} of ${detail.account.onboardingPlanDays}` : 'Plan day unavailable'}</strong><small>{detail.completedTasks} done · {detail.skippedTasks} skipped · {detail.pendingTasks} pending</small></div><div className="actions">{detail.account.status === 'RUNNING' ? <button className="secondary" onClick={() => void perform('close', () => window.accountApi.close(detail.account.id))}>Close browser</button> : <button className="secondary" onClick={() => void perform('open', () => window.accountApi.open(detail.account.id))}>Open Facebook</button>}{detail.account.onboardingStatus === 'WARMING' && <><button className="secondary" onClick={() => void perform('pause', () => window.onboardingApi.pause(detail.account.id))}>Pause</button><button className="primary" onClick={() => { if (window.confirm('Mark this account READY based on operator review? This is a workflow state, not a claim about Facebook safety.')) void perform('ready', () => window.onboardingApi.markReady(detail.account.id)); }}>Mark READY</button></>}{detail.account.onboardingStatus === 'PAUSED' && <button className="primary" onClick={() => void perform('resume', () => window.onboardingApi.resume(detail.account.id))}>Resume warm-up</button>}</div></div>
          <div className="manual-session"><div><strong>Manual session timer</strong><small>Tracks elapsed local time only; no mouse, typing, or Facebook content inspection.</small></div>{detail.activeSession ? <><code>{formatDuration(activeSeconds)}</code><button className="secondary" disabled={Boolean(busy)} onClick={() => void perform('stop-session', () => window.onboardingApi.stopSession(detail.account.id))}>Stop session</button></> : <button className="secondary" disabled={detail.account.onboardingStatus !== 'WARMING' || Boolean(busy)} onClick={() => void perform('start-session', () => window.onboardingApi.startSession(detail.account.id))}>Start session</button>}</div>
          <label>Local onboarding notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={4000} placeholder="Profile completed; checkpoint appeared on Day 2…" /></label><button className="secondary" onClick={() => void perform('notes', () => window.onboardingApi.updateNotes(detail.account.id, notes))}>Save notes</button>
          <div className="onboarding-tasks"><h3>Daily checklist</h3>{detail.tasks.map((task) => <div className={`warmup-task ${task.status.toLowerCase()} ${task.dayNumber === detail.currentDay ? 'today' : ''}`} key={task.id}>{editing?.id === task.id ? <TaskEditor task={editing} groups={groups} onChange={setEditing} onCancel={() => setEditing(undefined)} onSave={() => void perform(task.id, async () => { await window.onboardingApi.updateTask({ taskId: editing.id, title: editing.title, description: editing.description, groupId: editing.groupId }); setEditing(undefined); })} /> : <><div className="task-day">Day {task.dayNumber}</div><div className="task-copy"><strong>{task.title}</strong><p>{task.description}</p><small>{task.type.replaceAll('_', ' ')}{task.groupName ? ` · ${task.groupName}` : ''}{task.completedAt ? ` · ${new Date(task.completedAt).toLocaleString()}` : ''}</small></div><div className="task-actions">{task.type !== 'MANUAL_TASK' && <button className="action-button" disabled={Boolean(busy)} onClick={() => void taskAction(task)}>{task.type === 'OPEN_GROUP' ? 'Open group' : task.type === 'HEALTH_CHECK' ? 'Health check' : 'Open Facebook'}</button>}<button className="icon-button" onClick={() => setEditing(task)}>Edit</button>{task.status !== 'DONE' && <button className="action-button" disabled={detail.account.onboardingStatus !== 'WARMING'} onClick={() => void perform(task.id, () => window.onboardingApi.setTaskStatus({ taskId: task.id, status: 'DONE' }))}>Done</button>}{task.status !== 'SKIPPED' && <button className="action-button" disabled={detail.account.onboardingStatus !== 'WARMING'} onClick={() => void perform(task.id, () => window.onboardingApi.setTaskStatus({ taskId: task.id, status: 'SKIPPED' }))}>Skip</button>}{task.status !== 'PENDING' && <button className="icon-button" disabled={detail.account.onboardingStatus !== 'WARMING'} onClick={() => void perform(task.id, () => window.onboardingApi.setTaskStatus({ taskId: task.id, status: 'PENDING' }))}>Reset</button>}</div></>}</div>)}</div>
        </>}</>}</section></div></main>;
}

function TaskEditor({ task, groups, onChange, onCancel, onSave }: { task: WarmUpTask; groups: FacebookGroup[]; onChange: (task: WarmUpTask) => void; onCancel: () => void; onSave: () => void }) { return <div className="task-editor"><label>Title<input value={task.title} onChange={(event) => onChange({ ...task, title: event.target.value })} /></label><label>Description<textarea value={task.description} onChange={(event) => onChange({ ...task, description: event.target.value })} /></label>{task.type === 'OPEN_GROUP' && <label>Assigned group<select value={task.groupId ?? ''} onChange={(event) => onChange({ ...task, groupId: event.target.value || undefined })}><option value="">Choose when opening</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></label>}<div className="actions"><button className="secondary" onClick={onCancel}>Cancel</button><button className="primary" onClick={onSave}>Save task</button></div></div>; }
function formatDuration(seconds: number): string { const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }
