import { useCallback, useEffect, useMemo, useState } from 'react';
import type { AccountOnboarding, AccountSessionDetail, OnboardingOverview, OnboardingPlanTemplate, WarmUpTask } from '@shared/types';

export function OnboardingPage({ initialAccountId, onError }: { initialAccountId?: string; onError: (error: unknown) => void }) {
  const [overview, setOverview] = useState<OnboardingOverview>(); const [templates, setTemplates] = useState<OnboardingPlanTemplate[]>([]); const [selectedId, setSelectedId] = useState(initialAccountId ?? ''); const [onboarding, setOnboarding] = useState<AccountOnboarding>(); const [session, setSession] = useState<AccountSessionDetail>(); const [templateId, setTemplateId] = useState<'BASIC_3_DAY' | 'BASIC_5_DAY'>('BASIC_3_DAY'); const [notes, setNotes] = useState(''); const [sessionNote, setSessionNote] = useState(''); const [editing, setEditing] = useState<WarmUpTask>(); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState(''); const [groupId, setGroupId] = useState(''); const [operatorUrl, setOperatorUrl] = useState(''); const [now, setNow] = useState(Date.now());
  const loadOverview = useCallback(async () => { try { const value = await window.onboardingApi.overview(); setOverview(value); if (!selectedId && value.accounts.length) setSelectedId(value.accounts[0].account.id); } catch (error) { onError(error); } }, [onError, selectedId]);
  const loadDetail = useCallback(async () => { if (!selectedId) { setOnboarding(undefined); setSession(undefined); return; } try { const [plan, sessionDetail] = await Promise.all([window.onboardingApi.get(selectedId), window.onboardingApi.sessionDetail(selectedId)]); setOnboarding(plan); setSession(sessionDetail); setNotes(plan.account.onboardingNotes ?? ''); if (!groupId && sessionDetail.assignedGroups.length) setGroupId(sessionDetail.assignedGroups[0].id); } catch (error) { onError(error); } }, [groupId, onError, selectedId]);
  useEffect(() => { void window.onboardingApi.templates().then(setTemplates).catch(onError); void loadOverview(); const unsubscribe = window.onboardingApi.onChanged(() => { void loadOverview(); void loadDetail(); }); return unsubscribe; }, [loadDetail, loadOverview, onError]);
  useEffect(() => { void loadDetail(); }, [loadDetail]);
  useEffect(() => { if (session?.activeSession?.status !== 'ACTIVE') return; const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, [session?.activeSession?.status]);
  async function perform(label: string, operation: () => Promise<unknown>) { setBusy(label); setNotice(''); try { await operation(); await Promise.all([loadOverview(), loadDetail()]); } catch (error) { onError(error); } finally { setBusy(''); } }
  async function navigate(destination: 'HOME' | 'NOTIFICATIONS' | 'URL') { if (!session) return; await perform(`nav-${destination}`, async () => { const result = await window.onboardingApi.navigateSession({ accountId: session.account.id, destination, url: destination === 'URL' ? operatorUrl : undefined }); setNotice(result.status === 'OPENED' ? 'Page opened in the existing persistent profile.' : result.reason ?? 'Manual user action required.'); }); }
  const elapsed = useMemo(() => { const active = session?.activeSession; if (!active) return 0; return active.durationSeconds + (active.status === 'ACTIVE' && active.activeStartedAt ? Math.max(0, Math.floor((now - Date.parse(active.activeStartedAt)) / 1000)) : 0); }, [now, session?.activeSession]);
  const account = session?.account ?? onboarding?.account; const active = session?.activeSession; const currentProgress = session?.dailyProgress.find((day) => day.dayNumber === onboarding?.currentDay); const targetComplete = currentProgress?.completed === true; const displayedElapsed = active ? elapsed : currentProgress?.durationSeconds ?? 0; const displayedTarget = active?.targetDurationSeconds ?? currentProgress?.targetDurationSeconds ?? (session?.settings.targetDurationMinutes ?? 30) * 60;
  return <main className="content"><div className="page-heading"><div><h2>Account Session Assistant</h2><p>Local timers and operator-triggered navigation. Facebook browsing and social interactions remain entirely manual.</p></div><div className="heading-actions"><button className="danger" disabled={Boolean(busy)} onClick={() => { if (window.confirm('Stop every active account session and close its managed browser?')) void perform('stop-all', () => window.onboardingApi.stopAllSessions()); }}>STOP ALL ACCOUNT SESSIONS</button><button className="secondary" onClick={() => void Promise.all([loadOverview(), loadDetail()])}>Refresh</button></div></div>
    {overview && <div className="stat-grid onboarding-stats"><Stat label="New" value={overview.counts.NEW} detail="onboarding not started"/><Stat label="Warming" value={overview.counts.WARMING} detail="operator workflow active"/><Stat label="Ready" value={overview.counts.READY} detail="explicitly marked"/><Stat label="Paused" value={overview.counts.PAUSED} detail="manual action required"/><Stat label="Today’s tasks" value={overview.todayTasks.length} detail={`${overview.completedToday} completed today`}/></div>}
    {notice && <div className="notice success"><span>{notice}</span><button onClick={() => setNotice('')}>×</button></div>}
    <div className="onboarding-layout"><section className="panel onboarding-account-list"><div className="panel-heading"><h3>Accounts</h3><span>{overview?.accounts.length ?? 0}</span></div>{overview?.accounts.map((item) => <button key={item.account.id} className={selectedId === item.account.id ? 'onboarding-account active' : 'onboarding-account'} onClick={() => { setSelectedId(item.account.id); setGroupId(''); }}><strong>{item.account.name}</strong><span className={`status-badge status-${item.account.onboardingStatus.toLowerCase()}`}>{item.account.onboardingStatus}</span><small>{item.currentDay ? `Day ${item.currentDay} / ${item.account.onboardingPlanDays}` : 'Plan not started'}</small></button>)}</section>
      <section className="panel onboarding-detail">{!account || !onboarding || !session ? <div className="muted-block">Select an account.</div> : <><div className="panel-heading"><div><h3>{account.name}</h3><small>{onboarding.currentDay ? `Day ${onboarding.currentDay} / ${account.onboardingPlanDays}` : 'Onboarding not started'} · persistent profile {account.profileName}</small></div><span className={`status-badge status-${account.onboardingStatus.toLowerCase()}`}>{account.onboardingStatus}</span></div>
        {account.onboardingPausedReason && <div className="inline-warning">Manual user action required: {account.onboardingPausedReason}</div>}
        {account.onboardingStatus === 'NEW' ? <div className="onboarding-start"><label>Operator onboarding plan<select value={templateId} onChange={(event) => setTemplateId(event.target.value as typeof templateId)}>{templates.map((template) => <option key={template.id} value={template.id}>{template.name} · {template.days} days</option>)}</select></label><p>{templates.find((template) => template.id === templateId)?.description}</p><button className="primary" disabled={Boolean(busy)} onClick={() => void perform('start-onboarding', () => window.onboardingApi.start({ accountId: account.id, templateId }))}>Start onboarding</button></div> : <>
          <section className="session-card"><div className="session-card-heading"><div><small>Today’s account session</small><strong>{formatDuration(displayedElapsed)} / {formatDuration(displayedTarget)}</strong></div><span className={`status-badge status-${targetComplete && !active ? 'completed' : (active?.status ?? 'stopped').toLowerCase()}`}>{targetComplete && !active ? '✓ TARGET COMPLETE' : active?.status ?? 'NOT RUNNING'}</span></div>{targetComplete && !active && <div className="notice success session-complete-notice">Daily session target reached. {account.status === 'RUNNING' ? 'Browser remains open for manual use.' : 'Managed timer is complete.'}</div>}<div className="session-health-grid"><Metric label="Browser" value={account.status === 'RUNNING' ? 'OPEN' : account.status}/><Metric label="Health" value={account.lastHealthStatus ?? 'UNKNOWN'}/><Metric label="Proxy" value={account.proxyEnabled ? account.proxyStatus : 'DIRECT'}/><Metric label="Outbound IP" value={account.lastProxyTestIp ?? '—'}/></div>
            {!active ? <div className="session-start-row"><div><label>Daily target<select value={session.settings.targetDurationMinutes} onChange={(event) => void perform('settings', () => window.onboardingApi.updateSessionSettings({ targetDurationMinutes: Number(event.target.value), autoCloseBrowserAfterTarget: session.settings.autoCloseBrowserAfterTarget }))}>{[10, 15, 20, 30, 45, 60].map((minutes) => <option key={minutes} value={minutes}>{minutes} minutes</option>)}</select></label><label className="check-row"><input type="checkbox" checked={session.settings.autoCloseBrowserAfterTarget} onChange={(event) => void perform('settings', () => window.onboardingApi.updateSessionSettings({ targetDurationMinutes: session.settings.targetDurationMinutes, autoCloseBrowserAfterTarget: event.target.checked }))}/>Close browser automatically when target is reached</label></div>{targetComplete ? <button className="secondary" disabled={Boolean(busy) || account.status === 'RUNNING'} onClick={() => void perform('manual-open', () => window.accountApi.open(account.id))}>Open Facebook Manually</button> : <button className="primary" disabled={Boolean(busy) || account.onboardingStatus === 'PAUSED'} onClick={() => void perform('start-session', () => window.onboardingApi.startAssistedSession({ accountId: account.id }))}>Start Session</button>}</div> : <><label>Optional local session note<input value={sessionNote} maxLength={2000} onChange={(event) => setSessionNote(event.target.value)} placeholder="Operational note only; do not enter credentials or Facebook content."/></label><div className="session-controls"><button className="secondary" disabled={Boolean(busy) || active.status !== 'ACTIVE'} onClick={() => void perform('pause-session', () => window.onboardingApi.pauseAssistedSession(account.id))}>Pause Timer</button><button className="secondary" disabled={Boolean(busy) || active.status !== 'PAUSED'} onClick={() => void perform('resume-session', () => window.onboardingApi.resumeAssistedSession(account.id))}>Resume Timer</button><button className="danger" disabled={Boolean(busy)} onClick={() => { if (window.confirm('End this account session? The browser will remain available until you close it.')) void perform('end-session', async () => { await window.onboardingApi.endAssistedSession({ accountId: account.id, operatorNote: sessionNote }); setSessionNote(''); }); }}>End Session</button></div></>}
          </section>
          <section className="session-shortcuts"><div className="panel-heading"><div><h3>Operator navigation shortcuts</h3><small>Each page opens only after you press its button. No autonomous browsing occurs.</small></div></div><div className="actions"><button className="secondary" disabled={!active || Boolean(busy)} onClick={() => void navigate('HOME')}>Open Facebook</button><button className="secondary" disabled={!active || Boolean(busy)} onClick={() => void navigate('NOTIFICATIONS')}>Open Notifications</button><select value={groupId} onChange={(event) => setGroupId(event.target.value)}><option value="">Assigned group…</option>{session.assignedGroups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select><button className="secondary" disabled={!active || !groupId || Boolean(busy)} onClick={() => void perform('group', async () => { const result = await window.onboardingApi.openSessionGroup(account.id, groupId); setNotice(result.status === 'OPENED' ? 'Assigned group opened.' : result.reason ?? 'Manual user action required.'); })}>Open Assigned Group</button></div><div className="session-url-row"><input value={operatorUrl} onChange={(event) => setOperatorUrl(event.target.value)} placeholder="https://www.facebook.com/page-or-profile"/><button className="secondary" disabled={!active || !operatorUrl || Boolean(busy)} onClick={() => void navigate('URL')}>Open URL</button></div><div className="actions"><button className="secondary" disabled={account.status !== 'RUNNING' || Boolean(busy)} onClick={() => void perform('health', async () => { const result = await window.accountApi.healthCheck(account.id); setNotice(`Health check: ${result.status}${result.reason ? ` · ${result.reason}` : ''}`); })}>Health Check</button><button className="secondary" disabled={account.status !== 'RUNNING' || Boolean(busy)} onClick={() => void perform('close-browser', () => window.accountApi.close(account.id))}>Close Browser</button></div></section>
          <section className="session-progress"><div className="panel-heading"><h3>Daily progress</h3><span>{session.dailyProgress.filter((day) => day.completed).length}/{session.dailyProgress.length}</span></div>{session.dailyProgress.map((day) => <div className="progress-row" key={day.dayNumber}><strong>Day {day.dayNumber}</strong><div><span style={{ width: `${Math.min(100, day.durationSeconds / day.targetDurationSeconds * 100)}%` }}/></div><small>{formatMinutes(day.durationSeconds)} / {formatMinutes(day.targetDurationSeconds)} {day.completed ? '✓' : ''}</small></div>)}</section>
          <section className="eligibility-card"><div><h3>READY eligibility</h3><small>This is a local workflow check, never a Facebook safety claim.</small></div><ul><Eligibility ok={session.eligibility.requiredDaysCompleted} text="Required session days completed"/><Eligibility ok={session.eligibility.healthReady} text="Current health READY"/><Eligibility ok={session.eligibility.proxyReady} text="Proxy WORKING or Direct selected"/><Eligibility ok={session.eligibility.noActiveCheckpoint} text="No active checkpoint"/></ul>{account.onboardingStatus === 'WARMING' && <button className="primary" onClick={() => { const warning = session.eligibility.eligible ? '' : 'Eligibility requirements are incomplete. '; if (window.confirm(`${warning}Mark READY based on your own operator review?`)) void perform('ready', () => window.onboardingApi.markReady(account.id)); }}>Mark READY</button>}{account.onboardingStatus === 'PAUSED' && <button className="primary" onClick={() => void perform('resume-onboarding', () => window.onboardingApi.resume(account.id))}>Resume onboarding</button>}</section>
          <section className="session-history"><div className="panel-heading"><h3>Session history</h3><span>{session.sessions.length}</span></div>{session.sessions.length ? session.sessions.slice(0, 12).map((item) => <div className="history-row" key={item.id}><div><strong>Day {item.onboardingDay} · {item.status}</strong><small>{new Date(item.startedAt).toLocaleString()} · {item.completionReason ?? 'in progress'}{item.operatorNote ? ` · ${item.operatorNote}` : ''}</small></div><code>{formatDuration(item.durationSeconds)}</code></div>) : <div className="muted-block">No managed account sessions yet.</div>}</section>
          <details className="optional-checklist"><summary>Optional onboarding checklist and local notes</summary><label>Local onboarding notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={4000}/></label><button className="secondary" onClick={() => void perform('notes', () => window.onboardingApi.updateNotes(account.id, notes))}>Save notes</button><div className="onboarding-tasks">{onboarding.tasks.map((task) => <TaskRow key={task.id} task={task} editing={editing} setEditing={setEditing} perform={perform} accountStatus={account.onboardingStatus}/>)}</div></details>
        </>}</>}</section></div></main>;
}

function TaskRow({ task, editing, setEditing, perform, accountStatus }: { task: WarmUpTask; editing?: WarmUpTask; setEditing: (task?: WarmUpTask) => void; perform: (label: string, operation: () => Promise<unknown>) => Promise<void>; accountStatus: string }) { if (editing?.id === task.id) return <div className="warmup-task"><div className="task-editor"><label>Title<input value={editing.title} onChange={(event) => setEditing({ ...editing, title: event.target.value })}/></label><label>Description<textarea value={editing.description} onChange={(event) => setEditing({ ...editing, description: event.target.value })}/></label><div className="actions"><button className="secondary" onClick={() => setEditing(undefined)}>Cancel</button><button className="primary" onClick={() => void perform(task.id, async () => { await window.onboardingApi.updateTask({ taskId: editing.id, title: editing.title, description: editing.description, groupId: editing.groupId }); setEditing(undefined); })}>Save</button></div></div></div>; const systemManaged = task.type === 'HEALTH_CHECK' || task.type === 'OPEN_FACEBOOK'; return <div className={`warmup-task ${task.status.toLowerCase()}`}><div className="task-day">Day {task.dayNumber}</div><div className="task-copy"><strong>{task.title}</strong><p>{task.description}</p><small>{systemManaged ? 'SYSTEM TASK' : 'MANUAL OPTIONAL TASK'} · {task.status}</small></div><div className="task-actions"><button className="icon-button" onClick={() => setEditing(task)}>Edit</button>{!systemManaged && task.status !== 'DONE' && <button className="action-button" disabled={accountStatus !== 'WARMING'} onClick={() => void perform(task.id, () => window.onboardingApi.setTaskStatus({ taskId: task.id, status: 'DONE' }))}>Done</button>}</div></div>; }
function Stat({ label, value, detail }: { label: string; value: number; detail: string }) { return <div className="stat-card"><small>{label}</small><strong>{value}</strong><span>{detail}</span></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><strong>{value}</strong></div>; }
function Eligibility({ ok, text }: { ok: boolean; text: string }) { return <li className={ok ? 'ok' : ''}>{ok ? '✓' : '○'} {text}</li>; }
function formatDuration(seconds: number): string { const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); return `${hours ? `${String(hours).padStart(2, '0')}:` : ''}${String(minutes).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }
function formatMinutes(seconds: number): string { return `${Math.floor(seconds / 60)}m`; }
