import { useCallback, useEffect, useState } from 'react';
import type { PublishingEngineStatus } from '@shared/types';

export function PublishingPage({ onError }: { onError: (error: unknown) => void }) {
  const [status, setStatus] = useState<PublishingEngineStatus>();
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setStatus(await window.publishApi.status()); } catch (error) { onError(error); } }, [onError]);
  useEffect(() => { void load(); const unsubscribe = window.publishApi.onChanged(() => void load()); const timer = window.setInterval(() => void load(), 5000); return () => { unsubscribe(); window.clearInterval(timer); }; }, [load]);
  async function stop() { setBusy(true); try { await window.publishApi.stopPublishing?.(); await load(); } catch (error) { onError(error); } finally { setBusy(false); } }
  async function arm() { setBusy(true); try { await window.publishApi.armScheduler?.(Boolean(window.confirm('Acknowledge the overdue backlog and arm scheduled publishing for this session?'))); await load(); } catch (error) { onError(error); } finally { setBusy(false); } }
  async function exportReport() { try { await window.publishApi.exportReport?.(); } catch (error) { onError(error); } }
  if (!status) return <main className="content"><div className="empty-state">Loading publishing...</div></main>;
  const canary = status.settings.canaryMode !== false;
  return <main className="content">
    <div className="page-heading"><div><h2>Publishing</h2><p>Visible-browser execution, scheduler activity, selector health, and reconciliation.</p></div><div className="heading-actions"><span className={'engine-badge ' + (status.settings.enabled ? 'on' : 'off')}>ENGINE {status.settings.enabled ? 'ON' : 'OFF'}</span><span className="engine-badge off">{status.settings.executionMode.replace('_', ' ')}</span><span className={'engine-badge ' + (canary ? 'on' : 'off')}>CANARY {canary ? 'ON' : 'OFF'}</span><button className="secondary" onClick={() => void exportReport()}>Export report</button><button className="secondary" disabled={busy || status.schedulerArmed} onClick={() => void arm()}>Arm scheduler</button><button className="danger" disabled={busy || (!status.schedulerArmed && !status.running.length)} onClick={() => void stop()}>Stop Publishing</button></div></div>
    {canary && status.settings.executionMode === 'LIVE' && <div className="safety-card"><div className="safety-icon">!</div><div><strong>CANARY LIVE PUBLISH</strong><p>Only one explicit item may run. A fresh matching preflight is required for the same account, group, selector version, and snapshot.</p></div></div>}
    <div className="stat-grid"><Stat label="Scheduler" value={status.schedulerArmed ? status.tickRunning ? 'RUNNING' : 'ARMED' : 'DISARMED'} detail={(status.overdueCount ?? status.dueCount) + ' overdue item(s)'} /><Stat label="Executing" value={String(status.running.length)} detail={'max ' + status.settings.maxConcurrentAccounts + ' accounts'} /><Stat label="Blocked accounts" value={String(status.blockedAccounts.length)} detail="login/checkpoint circuits" /><Stat label="Readiness" value={status.readiness.replace('_', ' ')} detail={'selectors ' + status.selectorVersion} /></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h3>Currently executing</h3><span>{status.running.length}</span></div>{status.running.length ? <div className="stack-list">{status.running.map((item) => <div className="stack-row" key={item.id}><div><strong>CANARY RUNNING · {item.accountName} → {item.groupName}</strong><small>{item.draftTitle}</small></div><span className="status-badge status-running">RUNNING</span></div>)}</div> : <div className="muted-block">No active publishing operations.</div>}</section><section className="panel"><div className="panel-heading"><h3>Blocked accounts</h3><span>{status.blockedAccounts.length}</span></div>{status.blockedAccounts.length ? <div className="stack-list">{status.blockedAccounts.map((block) => <div className="stack-row" key={block.accountId}><div><strong>{block.accountName}</strong><small>{block.message}</small></div><span className="status-badge status-checkpoint">{block.reason}</span></div>)}</div> : <div className="muted-block">No blocked accounts.</div>}</section></div>
    <section className="panel operations-recent"><div className="panel-heading"><h3>Selector health</h3><span>{status.recentProbes.length} recent probes</span></div>{status.recentProbes.length ? <div className="table-wrap"><table><thead><tr><th>Checked</th><th>Account / Group</th><th>Version</th><th>Status</th><th>Warnings</th></tr></thead><tbody>{status.recentProbes.map((probe) => <tr key={probe.id ?? probe.accountId + '-' + probe.checkedAt}><td>{new Date(probe.checkedAt).toLocaleString()}</td><td>{probe.accountId.slice(0, 8)} / {probe.groupId.slice(0, 8)}</td><td>{probe.selectorVersion}</td><td><span className={'status-badge status-' + probe.status.toLowerCase()}>{probe.status}</span></td><td>{probe.warnings.join(' ') || '—'}</td></tr>)}</tbody></table></div> : <div className="muted-block">No selector probes yet. Use Queue → Preflight.</div>}</section>
    <section className="panel operations-recent"><div className="panel-heading"><h3>Recent attempts</h3><span>{status.recentAttempts.length}</span></div>{status.recentAttempts.length ? <div className="table-wrap"><table><thead><tr><th>Started</th><th>Queue</th><th>Attempt</th><th>Mode</th><th>Status</th><th>Result</th><th>Error</th></tr></thead><tbody>{status.recentAttempts.map((attempt) => <tr key={attempt.id}><td>{new Date(attempt.startedAt).toLocaleString()}</td><td>{attempt.queueItemId.slice(0, 8)}</td><td>#{attempt.attemptNumber}</td><td>{attempt.executionMode}</td><td><span className={'status-badge status-' + attempt.status.toLowerCase()}>{attempt.status}</span></td><td>{attempt.result ?? '—'}</td><td>{attempt.errorMessage ?? '—'}</td></tr>)}</tbody></table></div> : <div className="muted-block">No publishing attempts yet.</div>}</section>
  </main>;
}

function Stat({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="stat-card"><small>{label}</small><strong>{value}</strong><span>{detail}</span></div>; }
