import { useCallback, useEffect, useState } from 'react';
import type { Draft, FacebookAccount, FacebookGroup, PreflightResult, PublishAttempt, QueueItem, QueuePreview, QueueStatus, QueueTarget, ReconciliationRecord } from '@shared/types';

type Props = { accounts: FacebookAccount[]; onError: (error: unknown) => void };
const queueStatuses: QueueStatus[] = ['PENDING', 'PAUSED', 'RUNNING', 'SUBMITTED', 'SUCCEEDED', 'FAILED', 'NEEDS_ATTENTION', 'CANCELLED'];

export function QueuePage({ accounts, onError }: Props) {
  const [items, setItems] = useState<QueueItem[]>([]); const [drafts, setDrafts] = useState<Draft[]>([]); const [groups, setGroups] = useState<FacebookGroup[]>([]); const [loading, setLoading] = useState(true); const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [filterAccount, setFilterAccount] = useState(''); const [filterGroup, setFilterGroup] = useState(''); const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState('');
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [builder, setBuilder] = useState(false); const [draftId, setDraftId] = useState(''); const [selectedAccounts, setSelectedAccounts] = useState<string[]>([]); const [targets, setTargets] = useState<QueueTarget[]>([]); const [scheduledAt, setScheduledAt] = useState(''); const [preview, setPreview] = useState<QueuePreview>(); const [detail, setDetail] = useState<QueueItem>(); const [attempts, setAttempts] = useState<PublishAttempt[]>([]); const [reconciliations, setReconciliations] = useState<ReconciliationRecord[]>([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const [queue, draftList, groupList] = await Promise.all([window.queueApi.list({ search: search || undefined, status: status ? status as QueueStatus : undefined, accountId: filterAccount || undefined, groupId: filterGroup || undefined, from: fromDate ? new Date(fromDate).toISOString() : undefined, to: toDate ? new Date(toDate).toISOString() : undefined }), window.draftApi.list({ status: 'READY' }), window.groupApi.list({})]); setItems(queue); setDrafts(draftList); setGroups(groupList); } catch (error) { onError(error); } finally { setLoading(false); } }, [filterAccount, filterGroup, fromDate, onError, search, status, toDate]);
  useEffect(() => { void load(); const unsubscribe = window.publishApi.onChanged(() => void load()); return unsubscribe; }, [load]);

  function toggleTarget(accountId: string, groupId: string) { setTargets((current) => current.some((target) => target.accountId === accountId && target.groupId === groupId) ? current.filter((target) => target.accountId !== accountId || target.groupId !== groupId) : [...current, { accountId, groupId }]); }
  async function inspect() { try { setPreview(await window.queueApi.preview({ draftId, targets, scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : undefined })); } catch (error) { onError(error); } }
  async function create() { try { await window.queueApi.create({ draftId, targets, scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : undefined }); setBuilder(false); setPreview(undefined); setTargets([]); await load(); } catch (error) { onError(error); } }
  async function openDetail(item: QueueItem) { setDetail(item); try { const [history, reconciliation] = await Promise.all([window.publishApi.attempts(item.id), window.publishApi.reconciliations(item.id)]); setAttempts(history); setReconciliations(reconciliation); } catch (error) { onError(error); } }
  async function runItems(ids: string[]) { const chosen = items.filter((item) => ids.includes(item.id)); const accountCount = new Set(chosen.map((item) => item.accountId)).size; const groupCount = new Set(chosen.map((item) => item.groupId)).size; let mode: 'DRY_RUN' | 'LIVE'; try { mode = (await window.publishApi.status()).settings.executionMode; } catch (error) { onError(error); return; } const action = mode === 'DRY_RUN' ? 'run a preflight and stop before Post' : 'click Facebook Post once per job'; if (!window.confirm(`Run ${chosen.length} job(s) across ${accountCount} account(s) and ${groupCount} group(s)? This will ${action}.`)) return; setBusy(true); try { await window.publishApi.runSelected(ids); setSelected(new Set()); await load(); } catch (error) { onError(error); } finally { setBusy(false); } }
  async function action(item: QueueItem, kind: string) { setBusy(true); try {
    if (kind === 'pause') await window.queueApi.pause(item.id); if (kind === 'resume') await window.queueApi.resume(item.id); if (kind === 'cancel') await window.queueApi.cancel(item.id); if (kind === 'delete' && window.confirm('Delete this cancelled queue item and its history?')) await window.queueApi.delete(item.id);
    if (kind === 'open-group') { if (!item.groupId || !item.accountId) throw new Error('The original account or group is no longer available.'); await window.groupApi.open(item.groupId, item.accountId); }
    if (kind === 'preflight') { const result = await window.publishApi.preflight(item.id); const message = formatPreflightResult(result); if (result.diagnosticPath && !result.passed && window.confirm(`${message}\n\nOpen the local composer diagnostic screenshot?`)) await window.publishApi.openPreflightDiagnostic(item.id); else window.alert(message); }
    if (kind === 'retry') { const history = await window.publishApi.attempts(item.id); const risky = history[0]?.irreversibleReached ?? false; if (!window.confirm(risky ? 'Facebook may already have accepted the previous post. Retry may publish a duplicate. Continue?' : 'Retry this failed queue item?')) return; await window.publishApi.retry(item.id, risky); }
    if (kind === 'resolve') { if (!window.confirm('Mark this item submitted without claiming verified publication?')) return; await window.publishApi.resolve(item.id); }
    if (kind === 'mark-submitted') { if (!window.confirm('Mark this item SUBMITTED? This records operator reconciliation but does not verify public publication.')) return; await window.publishApi.markSubmitted(item.id); }
    if (kind === 'mark-verified') { const evidence = window.prompt('Describe the visible evidence you confirmed in Facebook:'); if (!evidence) return; await window.publishApi.markVerified(item.id, evidence); }
    if (kind === 'requeue') { if (!window.confirm('Create a new queue item from this immutable snapshot?')) return; await window.publishApi.requeue({ queueId: item.id }); }
    await load();
  } catch (error) { onError(error); } finally { setBusy(false); } }

  const runnable = items.filter((item) => selected.has(item.id) && item.status === 'PENDING');
  return <main className="content"><div className="page-heading"><div><h2>Queue</h2><p>Immutable snapshots, controlled execution, and publishing evidence.</p></div><div className="heading-actions">{runnable.length > 0 && <button className="secondary" disabled={busy} onClick={() => void runItems(runnable.map((item) => item.id))}>Run selected ({runnable.length})</button>}<button className="primary" onClick={() => setBuilder(true)}>＋ Build queue</button></div></div>
    <div className="filters"><label>Search<input placeholder="Draft, account, or group" value={search} onChange={(event) => setSearch(event.target.value)} /></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{queueStatuses.map((value) => <option value={value} key={value}>{value.replaceAll('_', ' ')}</option>)}</select></label><label>Account<select value={filterAccount} onChange={(event) => setFilterAccount(event.target.value)}><option value="">All accounts</option>{accounts.map((account) => <option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label>Group<select value={filterGroup} onChange={(event) => setFilterGroup(event.target.value)}><option value="">All groups</option>{groups.map((group) => <option value={group.id} key={group.id}>{group.name}</option>)}</select></label><label>From<input type="datetime-local" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label>To<input type="datetime-local" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label></div>
    {loading ? <div className="empty-state">Loading queue…</div> : !items.length ? <div className="empty-state"><strong>Queue is empty</strong><p>Build a queue batch from a READY draft and active assignments.</p></div> : <div className="table-card"><div className="table-wrap"><table className="queue-table"><thead><tr><th></th><th>Status</th><th>Scheduled</th><th>Account / Group</th><th>Draft</th><th>Media</th><th>Result</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><input type="checkbox" disabled={item.status !== 'PENDING'} checked={selected.has(item.id)} onChange={() => setSelected((current) => { const next = new Set(current); if (next.has(item.id)) next.delete(item.id); else next.add(item.id); return next; })} /></td><td><span className={`status-badge status-${item.status.toLowerCase()}`}>{item.status}</span>{item.attentionReason && <small className="error-text" title={item.attentionReason}>{item.attentionReason}</small>}</td><td>{item.scheduledAt ? new Date(item.scheduledAt).toLocaleString() : 'Manual'}{item.scheduledAt && new Date(item.scheduledAt) <= new Date() && item.status === 'PENDING' && <small className="due-label">Due</small>}</td><td><strong>{item.accountName}</strong><small>{item.groupName}</small></td><td><button className="link-button" onClick={() => void openDetail(item)}><strong>{item.draftTitle}</strong></button><small>{item.body.slice(0, 70)}{item.body.length > 70 ? '…' : ''}</small></td><td>{item.media.length}</td><td>{item.latestAttempt?.result ?? item.latestAttempt?.status ?? '—'}</td><td><QueueActions item={item} busy={busy} onRun={() => void runItems([item.id])} onAction={(kind) => void action(item, kind)} /></td></tr>)}</tbody></table></div></div>}
    {builder && <QueueBuilder drafts={drafts} accounts={accounts} groups={groups} draftId={draftId} selectedAccounts={selectedAccounts} targets={targets} scheduledAt={scheduledAt} preview={preview} onDraft={setDraftId} onAccounts={setSelectedAccounts} onTarget={toggleTarget} onSchedule={setScheduledAt} onPreview={() => void inspect()} onCreate={() => void create()} onCancel={() => { setBuilder(false); setPreview(undefined); }} />}
    {detail && <QueueDetail item={detail} attempts={attempts} reconciliations={reconciliations} onClose={() => { setDetail(undefined); setAttempts([]); setReconciliations([]); }} onDiagnostic={(id) => void window.publishApi.openDiagnostic(id).catch(onError)} onDeleteDiagnostic={(id) => void window.publishApi.deleteDiagnostic(id).then(() => openDetail(detail)).catch(onError)} />}
  </main>;
}

function formatPreflightResult(result: PreflightResult): string {
  const postFound = (result.postButton.count ?? 0) > 0 || result.postButtonFound;
  const postEnabled = result.postButton.enabled === true;
  const reason = result.reason ?? result.postButton.reason ?? result.warnings[0];
  const candidates = result.triggerCandidates?.slice(0, 5).map((candidate, index) => `${index + 1}. role=${candidate.role ?? 'unknown'}${candidate.ariaLabel ? ` aria-label="${candidate.ariaLabel}"` : ''}${candidate.text ? ` text="${candidate.text}"` : ''}`).join('\n');
  const textboxCandidates = result.textboxCandidates?.slice(0, 5).map((candidate, index) => `${index + 1}. group=${candidate.groupId ?? 'unknown'} tag=${candidate.tag ?? 'unknown'} role=${candidate.role ?? 'unknown'} contenteditable=${candidate.contenteditable ?? 'unknown'}${candidate.ariaLabel ? ` aria-label="${candidate.ariaLabel}"` : ''}${candidate.placeholder ? ` placeholder="${candidate.placeholder}"` : ''}${candidate.ariaMultiline ? ` aria-multiline=${candidate.ariaMultiline}` : ''}${candidate.lexicalEditor ? ` lexical=${candidate.lexicalEditor}` : ''}${candidate.focusable === undefined ? '' : ` focusable=${candidate.focusable ? 'YES' : 'NO'}`}${candidate.visible === undefined ? '' : ` visible=${candidate.visible ? 'YES' : 'NO'}`}`).join('\n');
  const dialogs = result.dialogCandidates?.slice(0, 5).map((candidate, index) => `${index + 1}. title=${candidate.title ?? 'unknown'}${candidate.newAfterTrigger === undefined ? '' : ` newAfterTrigger=${candidate.newAfterTrigger ? 'YES' : 'NO'}`}${candidate.changedAfterTrigger ? ' changedAfterTrigger=YES' : ''}${candidate.visible === undefined ? '' : ` visible=${candidate.visible ? 'YES' : 'NO'}`}${candidate.foreground === undefined ? '' : ` foreground=${candidate.foreground ? 'YES' : 'NO'}`}`).join('\n');
  return [`Preflight ${result.passed ? 'PASSED' : 'FAILED'}`, `Selector: ${result.selectorVersion}`, `Group: ${result.group.status}`, `Composer: ${result.composerTrigger.status}`, result.triggerStrategy ? `Trigger strategy: ${result.triggerStrategy}` : '', candidates && result.composerTrigger.status !== 'FOUND' ? `Trigger candidates:\n${candidates}` : '', `Create Post dialog: ${result.createPostDialog?.status ?? 'NOT TESTED'}${result.createPostDialog?.count === undefined ? '' : ` (${result.createPostDialog.count})`}`, result.dialogTitle ? `Dialog title: ${result.dialogTitle}` : '', dialogs && result.createPostDialog?.status !== 'FOUND' ? `Dialog candidates:\n${dialogs}` : '', `Textbox: ${result.composerTextbox.status}`, result.textboxStrategy ? `Textbox strategy: ${result.textboxStrategy}` : '', result.rawEditorCount !== undefined ? `Raw editor candidates: ${result.rawEditorCount}` : '', result.logicalEditorCount !== undefined ? `Collapsed editor groups: ${result.logicalEditorCount}` : '', textboxCandidates && result.composerTextbox.status !== 'FOUND' ? `Textbox candidates:\n${textboxCandidates}` : '', `Editor: ${result.editorType ?? 'UNKNOWN'}`, `Content: ${result.contentObserved ? 'OBSERVED' : 'NOT OBSERVED'}`, `Entry: ${result.entryMethod ?? 'NOT USED'}`, `Post control: ${postFound ? 'FOUND' : 'NOT FOUND'}`, `Post enabled: ${postEnabled ? 'YES' : 'NO'}`, reason ? `Reason: ${reason}` : ''].filter(Boolean).join('\n');
}

function QueueActions({ item, busy, onRun, onAction }: { item: QueueItem; busy: boolean; onRun: () => void; onAction: (kind: string) => void }) { return <div className="actions">{item.status === 'PENDING' && <><button className="action-button" disabled={busy} onClick={onRun}>Run</button><button className="action-button" onClick={() => onAction('preflight')}>Preflight</button><button className="action-button" onClick={() => onAction('pause')}>Pause</button></>}{item.status === 'PAUSED' && <button className="action-button" onClick={() => onAction('resume')}>Resume</button>}{(item.status === 'SUBMITTED' || item.status === 'NEEDS_ATTENTION') && item.accountId && item.groupId && <button className="action-button" onClick={() => onAction('open-group')}>Open group</button>}{item.status === 'NEEDS_ATTENTION' && <button className="action-button" onClick={() => onAction('mark-submitted')}>Mark submitted</button>}{(item.status === 'SUBMITTED' || item.status === 'NEEDS_ATTENTION') && <button className="action-button" onClick={() => onAction('mark-verified')}>Mark verified</button>}{['PENDING', 'PAUSED', 'NEEDS_ATTENTION'].includes(item.status) && <button className="action-button" onClick={() => onAction('cancel')}>Cancel</button>}{['FAILED', 'NEEDS_ATTENTION'].includes(item.status) && <button className="action-button" onClick={() => onAction('retry')}>Retry</button>}{['SUBMITTED', 'FAILED', 'SUCCEEDED', 'CANCELLED'].includes(item.status) && <button className="action-button" onClick={() => onAction('requeue')}>Requeue</button>}{item.status === 'CANCELLED' && <button className="icon-button danger-text" onClick={() => onAction('delete')}>Delete</button>}</div>; }

function QueueBuilder({ drafts, accounts, groups, draftId, selectedAccounts, targets, scheduledAt, preview, onDraft, onAccounts, onTarget, onSchedule, onPreview, onCreate, onCancel }: { drafts: Draft[]; accounts: FacebookAccount[]; groups: FacebookGroup[]; draftId: string; selectedAccounts: string[]; targets: QueueTarget[]; scheduledAt: string; preview?: QueuePreview; onDraft: (id: string) => void; onAccounts: (ids: string[]) => void; onTarget: (accountId: string, groupId: string) => void; onSchedule: (value: string) => void; onPreview: () => void; onCreate: () => void; onCancel: () => void }) { return <div className="modal-backdrop"><div className="modal form-modal wide-modal"><div className="modal-header"><div><h3>Build queue batch</h3><p>Every target is revalidated immediately before execution.</p></div><button className="close-button" onClick={onCancel}>×</button></div><label>READY draft<select value={draftId} onChange={(event) => onDraft(event.target.value)}><option value="">Choose a draft</option>{drafts.map((draft) => <option key={draft.id} value={draft.id}>{draft.title}</option>)}</select></label><div className="queue-builder-grid"><div><h4>Accounts</h4><div className="check-list compact">{accounts.map((account) => <label className="check-row" key={account.id}><input type="checkbox" checked={selectedAccounts.includes(account.id)} onChange={() => onAccounts(selectedAccounts.includes(account.id) ? selectedAccounts.filter((id) => id !== account.id) : [...selectedAccounts, account.id])} />{account.name}</label>)}</div></div><div><h4>Active groups</h4><div className="check-list compact">{groups.filter((group) => group.active).map((group) => <div className="target-group" key={group.id}><strong>{group.name}</strong>{selectedAccounts.map((accountId) => <label className="check-row" key={accountId}><input type="checkbox" checked={targets.some((target) => target.accountId === accountId && target.groupId === group.id)} onChange={() => onTarget(accountId, group.id)} />{accounts.find((account) => account.id === accountId)?.name}</label>)}</div>)}</div></div></div><label>Schedule (local time; blank means manual)<input type="datetime-local" value={scheduledAt} onChange={(event) => onSchedule(event.target.value)} /></label><div className="modal-actions"><button className="secondary" onClick={onCancel}>Cancel</button><button className="secondary" disabled={!draftId || !targets.length} onClick={onPreview}>Preview</button><button className="primary" disabled={!preview || Boolean(preview.issues.length)} onClick={onCreate}>Create {targets.length} item(s)</button></div>{preview && <div className={`preview-box ${preview.issues.length ? 'has-errors' : ''}`}><strong>{preview.issues.length ? 'Review validation issues' : `${preview.targets.length} items ready`}</strong>{preview.issues.map((issue, index) => <div key={`${issue.code}-${index}`}>{issue.code}: {issue.message}</div>)}</div>}</div></div>; }

function QueueDetail({ item, attempts, reconciliations, onClose, onDiagnostic, onDeleteDiagnostic }: { item: QueueItem; attempts: PublishAttempt[]; reconciliations: ReconciliationRecord[]; onClose: () => void; onDiagnostic: (attemptId: string) => void; onDeleteDiagnostic: (attemptId: string) => void }) { return <div className="modal-backdrop"><div className="modal form-modal wide-modal queue-detail"><div className="modal-header"><div><h3>Queue snapshot</h3><p>Immutable content and execution history.</p></div><button className="close-button" onClick={onClose}>×</button></div><div className="snapshot-meta"><span>{item.accountName}</span><span>→</span><span>{item.groupName}</span><span className={`status-badge status-${item.status.toLowerCase()}`}>{item.status}</span></div><h4>{item.draftTitle}</h4><pre className="snapshot-body">{item.body}</pre>{item.linkUrl && <div className="snapshot-link">{item.linkUrl}</div>}<div className="media-grid">{item.media.map((media) => <div className="media-card compact-media" key={media.id}><strong>{media.originalName}</strong><small>{media.type} · #{media.sortOrder + 1}</small></div>)}</div>{reconciliations.length > 0 && <><h4 className="timeline-title">Operator reconciliation</h4><div className="stack-list">{reconciliations.map((record) => <div className="stack-row" key={record.id}><div><strong>{record.action}</strong><small>{record.evidence}</small></div><time>{new Date(record.createdAt).toLocaleString()}</time></div>)}</div></>}<h4 className="timeline-title">Execution history</h4>{attempts.length ? attempts.map((attempt) => <section className="attempt-card" key={attempt.id}><div className="panel-heading"><strong>Attempt {attempt.attemptNumber} · {attempt.executionMode}</strong><span className={`status-badge status-${attempt.status.toLowerCase()}`}>{attempt.status}</span></div>{attempt.events.map((event) => <div className="timeline-row" key={event.id}><time>{new Date(event.createdAt).toLocaleTimeString()}</time><strong>{event.eventType}</strong><span>{event.message ?? ''}</span></div>)}{attempt.receipt && <div className="receipt"><strong>Receipt: {attempt.receipt.result} ({attempt.receipt.verificationSource})</strong><span>{attempt.receipt.evidence}</span>{attempt.receipt.verificationEvidence && <span>Operator: {attempt.receipt.verificationEvidence}</span>}{attempt.receipt.postUrl && <span>{attempt.receipt.postUrl}</span>}</div>}{attempt.errorMessage && <div className="inline-error">{attempt.errorCode}: {attempt.errorMessage}</div>}{attempt.diagnosticAvailable && <div className="heading-actions"><button className="secondary" onClick={() => onDiagnostic(attempt.id)}>Open diagnostic</button><button className="secondary" onClick={() => onDeleteDiagnostic(attempt.id)}>Delete diagnostic</button></div>}</section>) : <div className="muted-block">No attempts yet.</div>}<div className="modal-actions"><button className="secondary" onClick={onClose}>Close</button></div></div></div>; }
