import { useEffect, useState } from 'react';
import type { PublishingSettings } from '@shared/types';

export function SettingsPage({ onError }: { onError: (error: unknown) => void }) {
  const [value, setValue] = useState<PublishingSettings>(); const [saving, setSaving] = useState(false);
  useEffect(() => { void window.settingsApi.getPublishing().then(setValue).catch(onError); }, [onError]);
  async function save() { if (!value) return; setSaving(true); try { setValue(await window.settingsApi.updatePublishing(value)); } catch (error) { onError(error); } finally { setSaving(false); } }
  if (!value) return <main className="content"><div className="empty-state">Loading settings…</div></main>;
  return <main className="content"><div className="page-heading"><div><h2>Settings</h2><p>Automatic execution is opt-in. Manual runs always require confirmation.</p></div><button className="primary" disabled={saving} onClick={() => void save()}>{saving ? 'Saving…' : 'Save settings'}</button></div><section className="panel settings-panel"><label className="engine-toggle"><input type="checkbox" checked={value.enabled} onChange={(event) => setValue({ ...value, enabled: event.target.checked })} /><span><strong>Publishing Engine</strong><small>{value.enabled ? 'Scheduled due items may run automatically.' : 'Automatic publishing is disabled.'}</small></span><b>{value.enabled ? 'ON' : 'OFF'}</b></label><div className="settings-grid"><label>Scheduler interval (seconds)<input type="number" min={15} max={300} value={value.schedulerIntervalSeconds} onChange={(event) => setValue({ ...value, schedulerIntervalSeconds: Number(event.target.value) })} /><small>15–300 seconds. No overlapping scheduler ticks.</small></label><label>Concurrent accounts<input type="number" min={1} max={3} value={value.maxConcurrentAccounts} onChange={(event) => setValue({ ...value, maxConcurrentAccounts: Number(event.target.value) })} /><small>One operation per account; 1–3 accounts globally.</small></label><label>Video readiness timeout (seconds)<input type="number" min={60} max={1800} value={value.videoUploadTimeoutSeconds} onChange={(event) => setValue({ ...value, videoUploadTimeoutSeconds: Number(event.target.value) })} /><small>Facebook must finish video processing before Post.</small></label></div><div className="safety-card"><div className="safety-icon">!</div><div><strong>Security challenges stop execution</strong><p>Login, checkpoint, CAPTCHA, identity, and recovery states require manual action. This application never attempts to bypass them.</p></div></div></section></main>;
}
